TRUNCATE TABLE publisher RESTART IDENTITY CASCADE;
-- Publisher data
----------------------------------------------
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (1, 'Bloomsbury Publishing', null, 'https://media-exp1.licdn.com/dms/image/C4E0BAQEDkPybVXr47Q/company-logo_200_200/0/1544531682586?e=2159024400&v=beta&t=JjAs9ok_PwgXA9CFsXKm3bt6fjbFI4N7SZRn4ajOUVg');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (102, 'Palok Publishers', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (105, 'গদ্যপদ্য', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (106, 'দি রয়েল পাবলিশার্স', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (109, 'প্রতিভা প্রকাশ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (110, 'কথামেলা প্রকাশন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (133, 'বেঙ্গল পাবলিকেশন্‌স', null, 'https://ds.rokomari.store/rokomari110/company/5cc15a9e8004_755.jpg');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (134, 'আদী প্রকাশন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (138, 'জ্যোৎস্না পাবলিশার্স', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (142, 'বিজয় প্রকাশ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (144, 'শুভ্র প্রকাশ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (150, 'আদিগন্ত প্রকাশন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (151, 'অন্যধারা', null, 'https://ds.rokomari.store/rokomari110/company/dac6d01b1_364.jpg');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (153, 'মহাকাল', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (157, 'মৌলি প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (158, 'শুভ প্রকাশন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (163, 'জয় প্রকাশন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (177, 'কুঁড়েঘর প্রকাশনী লিমিটেড', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (181, 'শুদ্ধস্বর', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (183, 'চমনপ্রকাশ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (198, 'বিপ্লবীদের কথা', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (199, 'শব্দশিল্প', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (209, 'প্রিয়মুখ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (211, 'তৃণলতা প্রকাশ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (215, 'শামস্‌ পাবলিকেশন্স', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (291, 'দ্বিমিক প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/436092935fd4_3594.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (293, 'হাতেখড়ি', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (303, 'ডেইলি স্টার বুকস', null, 'https://ds.rokomari.store/rokomari110/company/a0610fece_848.jpg');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (312, 'পুথিনিলয় প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (315, 'পাললিক সৌরভ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (317, 'আজাদ পাবলিকেশন্স', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (322, 'ক্র্যাট প্রকাশ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (327, 'রাত্রি প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (338, 'রাতুল গ্রন্থপ্রকাশ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (343, 'মৌ প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (348, 'সংরক্ষণ প্রকাশন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (225, 'চন্দ্রদীপ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (226, 'গোল্ডেন বুকস', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (227, 'স্বরবৃত্ত প্রকাশন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (228, 'যুক্ত প্রকাশনা', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (229, 'কবি প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (230, 'আলোঘর প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (237, 'শাহীন প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (238, 'সমগ্র প্রকাশন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (240, 'চিত্রা প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (244, 'মেলা প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (247, 'দেশ পাবলিকেশন’স', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (251, 'রূপ প্রকাশন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (254, 'সাহস পাবলিকেশন্স', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (255, 'চৈতন্য', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (285, 'আপন প্রকাশ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (21, 'দ্বিমিক প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/436092935fd4_3594.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (42, 'বসুন্ধরা প্রকাশন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (44, 'স্টুডেন্ট ওয়েজ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (45, 'মনন প্রকাশ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (46, 'বাঙলায়ন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (49, 'নওরোজ কিতাবিস্তান', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (50, 'অবধূত বইঘর', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (52, 'ওয়াল্ড নিউজ এজেন্সি', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (55, 'নবযুগ প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (56, 'মেরিট ফেয়ার প্রকাশন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (57, 'নওরোজ সাহিত্য সম্ভার', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (62, 'এশিয়া পাবলিকেশন্স', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (64, 'রিয়া প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (65, 'সাকী পাবলিশিং ক্লাব', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (68, 'প্রান্ত প্রকাশন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (69, 'কলি প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (70, 'কাশবন প্রকাশন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (72, 'নুসরাত প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (73, 'হাসি প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (74, 'অন্তরা', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (75, 'হিমু প্রকাশন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (77, 'নবরাগ প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (79, 'বর্ণায়ন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (82, 'মুক্তদেশ প্রকাশন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (86, 'মুক্তচিন্তা', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (88, 'সমতট', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (89, 'আশীর্বাদ প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (90, 'রাবেয়া বুক হাউস', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (91, 'আলেয়া বুক ডিপো', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (92, 'প্রচলন প্রকাশন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (94, 'বর্ষাদুপুর', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (96, 'প্রগতি পাবলিশার্স', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (97, 'দিব্য প্রকাশ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (101, 'রাবেয়া বুকস্', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (414, 'শিশুকিশোর প্রকাশন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (417, 'বঙ্গজ প্রকাশন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (432, 'কোয়ান্টাম ফাউন্ডেশন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (441, 'আলোকায়ন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (462, 'মাহি প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (482, 'Daffodil International University Press', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (484, 'অনুশীলন প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (529, 'অন্যপ্রকাশ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (530, 'বিশ্বসাহিত্য ভবন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (531, 'অনন্যা', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (533, 'উৎস প্রকাশন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (536, 'কথাপ্রকাশ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (537, 'ভাষাপ্রকাশ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (538, 'ইত্যাদি গ্রন্থ প্রকাশ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (540, 'শ্রাবণ প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (541, 'অনুপম প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (542, 'অন্বেষা প্রকাশন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (543, 'অবসর প্রকাশনা সংস্থা', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (544, 'আফসার ব্রাদার্স', null, 'https://ds.rokomari.store/rokomari110/company/69af2f2fe544_14.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (545, 'কাকলী প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (546, 'জ্ঞানকোষ প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (547, 'পার্ল পাবলিকেশন্স', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (548, 'প্রতীক প্রকাশনা সংস্থা', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (549, 'মাওলা ব্রাদার্স', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (550, 'সময় প্রকাশন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (552, 'সাগর পাবলিশার্স', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (553, 'সুবর্ণ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (557, 'আগামী প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (558, 'সাহিত্য প্রকাশ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (561, 'সিদ্দিকীয়া পাবলিকেশন্স', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (564, 'বিউটি বুক হাউস', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (565, 'বিজ্ঞান একাডেমী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (567, 'বিভাস', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (570, 'প্রথমা প্রকাশন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (571, 'সন্দেশ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (572, 'বুক ক্লাব', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (573, 'শৈশব', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (574, 'বিদ্যাপ্রকাশ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (575, 'রহমান বুকস', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (576, 'আবির বুকস', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (577, 'অঙ্কুর প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (579, 'বাংলাপ্রকাশ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (580, 'সাহিত্য কথা', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (581, 'সূচীপত্র', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (583, 'শোভা প্রকাশ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (584, 'উত্তরণ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (585, 'মূর্ধন্য', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (588, 'মাটিগন্ধা', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (589, 'বাংলাদেশ শিশুকেন্দ্র', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (590, 'বিশ্বসাহিত্য কেন্দ্র', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (591, 'হাওলাদার প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (594, 'ঝিঙেফুল', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (595, 'কালিকলম প্রকাশনা', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (596, 'জোনাকী প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (597, 'তাম্রলিপি', null, 'https://ds.rokomari.store/rokomari110/company/d79ef1da9_58.jpg');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (598, 'শিখা প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (599, 'শামীম পাবলিশার্স', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (600, 'তরফদার প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (601, 'তিশা বুক্‌স ট্রেড', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (602, 'বর্ণবিচিত্রা', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (603, 'সুচয়নী পাবলিশার্স', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (604, 'ঐতিহ্য', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (605, 'অ্যাডর্ন পাবলিকেশন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (606, 'Adorn Publication', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (608, 'সাহিত্যদেশ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (610, 'সাহিত্যমালা', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (611, 'অনিন্দ্য প্রকাশ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (612, 'জাগৃতি প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (613, 'অন্যরকম প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (614, 'নালন্দা', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (615, 'চারুলিপি প্রকাশন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (616, 'খান ব্রাদার্স অ্যান্ড কোম্পানি', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (617, 'একুশে বাংলা প্রকাশন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (618, 'সিসটেক পাবলিকেশন্স', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (619, 'শব্দশৈলী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (620, 'অক্ষর প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (624, 'জাতীয় সাহিত্য প্রকাশ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (625, 'গাজী প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (626, 'ঝিনুক প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (627, 'পাঞ্জেরী পাবলিকেশন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (628, 'আদর্শ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (630, 'পাঠক সমাবেশ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (631, 'প্রকৃতি', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (632, 'সমাচার', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (635, 'আরো প্রকাশন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (637, 'বৈশাখী প্রকাশ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (639, 'জনান্তিক', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (640, 'সৃজনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (642, 'ইতি প্রকাশন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (643, 'দি ইউনিভার্সেল একাডেমি', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (647, 'ন্যাশনাল পাবলিকেশন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (648, 'অয়ন প্রকাশন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (650, 'সেবা প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (651, 'জিনিয়াস পাবলিকেশন্স', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (652, 'শিকড়', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (653, 'জয়তী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (655, 'দি স্কাই পাবলিশার্স', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (656, 'বুকস্‌ ফেয়ার', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (658, 'রচনা প্রকাশ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (660, 'আহমদ পাবলিশিং হাউজ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (661, 'জ্ঞান বিতরণী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (664, 'আজকাল প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (665, 'মিজান পাবলিশার্স', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (666, 'রোদেলা প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (667, 'বাতিঘর প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/ef2d496af8d4_572.gif');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (671, 'সুলেখা প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (677, 'জনতা প্রকাশ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (679, 'কালান্তর প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (681, 'সালাউদ্দিন বই ঘর', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (361, 'মুন পাবলিকেশন্স', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (375, 'শিশু কানন', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (384, 'তূর্য প্রকাশনী', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (389, 'সালমা বুক ডিপো', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (391, 'পাণ্ডুলিপি', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (404, 'এ্যাবাকাস পাবলিকেশন্স', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (407, 'শিশু প্রকাশ', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
